made search index rebuild after site init optional

diff --git a/post_install_script b/post_install_script
--- a/post_install_script
+++ b/post_install_script
@@ -20,6 +20,11 @@ if [ -z ${BUILD_SUITE_URL} ]; then
     exit 1
 fi
 
+if [ -z ${SITEGENESIS_URL} ]; then
+    echo "===== Error: SITEGENESIS_URL is not set. Exiting now."
+    exit 1
+fi
+
 
 
 mkdir ~/.ssh
